### PR TITLE
Upgrading KPL/KCL libraries, replacing deprecated shutdown calls

### PR DESCRIPTION
**Pull request by etspaceman**
Upgrades per #24

### CODE REVIEW

**Comment by etspaceman** [comment]
Not sure why the travis build failed here. My tests pass locally and the failure seems related to an encryption key reference for travis.

**Comment by etspaceman** [comment]
Pinging @markglh... does this look OK?

**Comment by markglh** [comment]
Sorry @etspaceman I completely missed this! Thanks for taking care of that - I'll look into it today and see what the build issue is.

**Comment by markglh** [comment]
@etspaceman if you rebase from master that should build now :)

**Pull request merged**
